# Generated by Django 4.2.7 on 2023-11-05 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_movie_date_remove_movie_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 5, 11, 30, 25, 925146, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='hall',
            field=models.CharField(default='G35', max_length=5),
            preserve_default=False,
        ),
    ]
