# Generated by Django 4.2.8 on 2023-12-04 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_customer_created_at_customer_modified_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='modified_at',
        ),
    ]
