# Generated by Django 4.2.7 on 2023-12-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_customer_created_at_customer_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
